version: '3'
services:
  my-compose-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    ports: 
      - "3000:2000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev